services:
  - type: web
    name: student-collaboration-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
